### ISSUE TITLE
Valoraciones

### ISSUE THREAD

**Issue by alvarocastellano** [Galeon2098/CuidaME#101]
Crear sistema de valoraciones (como se ve en los [mockups](https://marvelapp.com/prototype/7d58gha/screen/93939789)). Habrá que crear la entidad y la funcionalidad. También hay que mirar bien de qué forma calcular la media de valoración: calcularla al renderizar el perfil del cuidador o cada vez que se haga una valoración.

Esto no es prioritario pero habría que darle una vuelta: Solo valorar personas que han trabajado para ti.

**Comment by jualeomad** [comment]
Hay que hacer algunas correcciones:

- No debe de haber media de valoración por oferta, la valoración es al cuidador. Los comentarios de la valoración serán también globales para el cuidador. Aunque como está un poco en el aire se puede seguir manteniendo la relación review-offer para futuras implementaciones.
- Las notas van de 0 a 5 y deben ser un desplegable, ahora está puesto como un input type="radio" y debería usarse más bien un select.
- Hay que ajustarlo a los mockups ([https://marvelapp.com/prototype/7d58gha/screen/93941792](https://marvelapp.com/prototype/7d58gha/screen/93941792))

Así debe de verse:



![Image](https://github.com/Galeon2098/CuidaME/assets/73229901/31bde0d2-475f-4e61-94bc-6501dce149ea)
