### ISSUE TITLE
Bluejay

### ISSUE THREAD

**Issue by Lucperrom** [Galeon2098/CuidaME#107]
Enlazar nuestro repo al Bluejay de ispp. Para hacerlo entrar en enseñanza virtual, entrar en el link de bluejay de ispp de control de equipos y seguir los pasos especificados en el readme de ese enlace

**Comment by Lucperrom** [comment]
Han enviado este comunicado hoy: "Aún hay grupos que faltan por inscribir sus repos. Intentaré dejar Bluejay calculando hoy a la tarde. Necesito configurar las horas de ejecución para que no se solapen, si conocen a algún compañero que no haya hecho el JOIN  de sus repositorios avísenle por favor. Muchas gracias"

**Comment by manueljgranados** [comment]
- Creado el registro a BlueJay en el enlace que nos facilitan
- Añadido el fichero info.yml a la rama master tal y como se indica en las instrucciones
- Agregado en README.md el enlace al Dashboard de BlueJay

**Comment by alvarocastellano** [comment]
BlueJay creado y funcionando correctamente.
