### ISSUE TITLE
Documento de feedback de usuarios piloto de pruebas

### ISSUE THREAD

**Issue by joaquin-restoy** [Galeon2098/CuidaME#113]
Crear un formulario (en excel, hojas de calculo de google o similares) para los usuarios pilotos que realizaran pruebas del proyecto basado en los diagramas de secuencia (Issue 61)

**Comment by joaquin-restoy** [comment]
Aprobacion de documento

**Comment by manueljgranados** [comment]
Revisado. Contiene todo lo necesario.
