### ISSUE TITLE
Manual instrucciones Docusaurus

### ISSUE THREAD

**Issue by manueljgranados** [Galeon2098/CuidaME#138]
Crear un breve manual de instrucciones para la creación, modificación y búsqueda de documentos en Docusaurus

**Comment by antsuagar** [comment]
Tarea realizada. Se ha añadido al Drive el documento _Manual de isntrucciones de Docusaurus_. En cuanto a la búsqueda, se ha añadido una barra de búsqueda a la aplicación(Issue #150 )
