### ISSUE TITLE
Análisis Videollamadas

### ISSUE THREAD

**Issue by jualeomad** [Galeon2098/CuidaME#139]
Ya que probablemente ninguno ha desarrollado algo de este tipo y a priori es algo complejo, es necesario un análisis de la tarea. Se deben buscar alternativas de desarrollo de las videollamadas y encontrar una buena subdivisión de la misma para que pueda ser realizada por 2 o 3 desarrolladores.

**Comment by Galeon2098** [comment]
1. Crear pagina (template sencilla), mostrar video de tu webcam (1 usuario) y permitir mas usuarios
2. Controles (quitar camara, micro, etc), permitir unirse a usuarios desde boton/solicitud/etc y añadir nombres de usuario
3. Estilos de la sala (FrontEnd) 

Aquí dejo el tutorial para hacerlo paso a paso: https://www.youtube.com/watch?v=Oxnz8Us1QAQ&t=2760s&ab_channel=DennisIvy
