### ISSUE TITLE
fix: Valoraciones

### ISSUE THREAD

**Issue by alvarocastellano** [Galeon2098/CuidaME#143]
VALORACIONES
-Al escribir una valoración peta si no se seleccionan estrellas
-Si rellenas correctamente "te permite valorar" ya que no ves ningún cambio y si lo intentas otra vez te dice que ya valorastes pero no muestra ningún comentario
-Comentario: otro cuidador puede valorar a otro cuidador

Backend: @JuanAntonioJimenezdelVillar , Frontend: @alvarocastellano  , Responsable principal: @JuanAntonioJimenezdelVillar

**Comment by alvarocastellano** [comment]
Tarea completada correctamente

**Comment by crigarher** [comment]
:D
