### ISSUE TITLE
PU: Testear aplicación del grupo de mañana

### ISSUE THREAD

**Issue by manueljgranados** [Galeon2098/CuidaME#155]
Issue responsabilidad de @manueljgranados 

Instrucciones: 
- Hay que probar todos los puntos indicados en la hoja de cálculo con nuestro nombre en Drive.
- Indicar en la columna "Errores encontrados" TODOS los errores que veamos en cada apartado.
- Indicar en la columna "Feedback" sugerencias para cada apartado.
- Para esta tarea se imputa, como máximo, **1 hora**. Se hace en menos tiempo así que procuremos esmerarnos en la descripción de cada error y, sobretodo, en el feedback aportado. (Recordad que esto lo repasan los profesores).
- Cuando alguien termine su testeo que lo indique añadiendo un comentario en esta issue.

Dirección del fichero de testeo: En el Drive, "Feedback - Grupo de mañana/Feedback aportado/Feedback1 - 10/03/2024/PU - nombreTesteador"

URL aplicación: https://musclemate-415920.oa.r.appspot.com/

**Comment by diemargon4** [comment]
Testeo terminado por mi parte

**Comment by joaquin-restoy** [comment]
Testeo terminado por mi tarde

**Comment by JuanAntonioJimenezdelVillar** [comment]
Testeo terminado por mi parte.

**Comment by jualeomad** [comment]
Testeo terminado por mi parte 👍

**Comment by mohanadabulatifa** [comment]
Testeo terminado por mi parte.

**Comment by manueljgranados** [comment]
Mi testeo está hecho también.

**Comment by antsuagar** [comment]
Testeo terminado por mi parte ✅

**Comment by GaVidalT** [comment]
Mi testeo está hecho también.

**Comment by dandiasua02** [comment]
Testeo terminado por mi parte.

**Comment by manueljgranados** [comment]
Hecho el feedback de todos los técnicos asignados a esta tarea.

Entregado el feedback a los compañeros del grupo de mañana.
