### ISSUE TITLE
feat: Foro (backend)

### ISSUE THREAD

**Issue by Lucperrom** [Galeon2098/CuidaME#159]
Funcionalidad estilo "foro coches": 
-Poder crear un "hilo" relacionado con un tema en concreto. El hilo debe tener un título, una descripción y la fecha de creación (fecha actual creada automáticamente).
-Dentro de ese hilo cualquier usuario puede añadir un comentario. Ese comentario tendrá: el nombre del usuario que lo publica y el comentario en sí.
-Todos los hilos creados deben poder listarse en un apartado de foro.
-Posibilidad de filtrado con una barra de búsqueda que te muestre todos aquellos hilos cuyo asunto contenga alguna de las palabras introducidas en el buscador.
-Posibilidad de ordenarlo por fecha de creación del hilo.

Para consultar todas las restricciones y reglas de negocio ver la descripción de la tarea #161

**Comment by crigarher** [comment]
Dentro del comentario voy a añadir también la fecha en la que se  creó el comentario, creo que es útil y así pueden ver si el comentario se hizo hace mucho o recientemente.
