### ISSUE TITLE
Arreglos barra de navegación

### ISSUE THREAD

**Issue by manueljgranados** [Galeon2098/CuidaME#176]
Ha de ser responsive y ser más similar a la definida en los mockups

**Comment by manueljgranados** [comment]
Issue pertenece a Épica #166

**Comment by antsuagar** [comment]
¿Con barra de navegación te refieres al filtro de búsqueda de ofertas?

**Comment by antsuagar** [comment]
¿El resultado que se busca es este? La primera imagen es la vista en PC y la segunda en smartphone.
![busqueda_pc](https://github.com/Galeon2098/CuidaME/assets/100385525/f08a5b98-8b43-4225-9cd4-1b731e218ec1)
![busqueda_movil](https://github.com/Galeon2098/CuidaME/assets/100385525/f40c7c08-1816-421a-8b2c-a73218bcd501)

**Comment by manueljgranados** [comment]
@antsuagar, la idea es que no haya texto pisando otro texto o simplemente saliéndose del control en el que está

**Comment by manueljgranados** [comment]
Me refiero al header... que sea responsive. Que en movil se salen los botones de la barra del header

**Comment by antsuagar** [comment]
Vale, entendido. ¿Dejo el filtro de búsqueda de ofertas cambiado o lo vuelvo a dejar como estaba?

**Comment by antsuagar** [comment]
Este es el resultado en smartphone. Si estás conforme abro pull request. 
Vista deslogueado
![header_logou](https://github.com/Galeon2098/CuidaME/assets/100385525/8a776cc5-a283-4c9c-b764-626ee0743be2)
Vista cliente
![header_cliente](https://github.com/Galeon2098/CuidaME/assets/100385525/5254f7b0-194c-42fc-81bd-4f3ab6f9c1db)
Vista cuidador
![header_cuidador](https://github.com/Galeon2098/CuidaME/assets/100385525/c4226ca4-1c1d-43d6-9594-226bd868ce10)

**Comment by manueljgranados** [comment]
@antsuagar , queda muy elegante... buen trabajo.

Crea la PR
