### ISSUE TITLE
PU: Testear app del grupo de mañana 2

### ISSUE THREAD

**Issue by manueljgranados** [Galeon2098/CuidaME#184]
URL a testear: https://musclemate-sprint2.oa.r.appspot.com/

Excel guia: "Drive/Feedback - Grupo de Mañana/Feedback Aportado/Feedback 2 - 17/03/2024/PU - Nombre del Técnico"

Hay que tenerlo hecho antes del lunes a las 15:00

Cuando un técnico termine de testear ha de indicarlo con un comentario en esta issue

**Comment by manueljgranados** [comment]
Test hecho

**Comment by joaquin-restoy** [comment]
Test hecho

**Comment by alvarocastellano** [comment]
Test hecho

**Comment by carlosdelrioperez** [comment]
Test hecho

**Comment by dandiasua02** [comment]
Test hecho

**Comment by JuanAntonioJimenezdelVillar** [comment]
Test hecho

**Comment by jualeomad** [comment]
Test hecho

**Comment by manueljgranados** [comment]
Tests hechos y entregados al grupo de mañana
