### ISSUE TITLE
Correcciones

### ISSUE THREAD

**Issue by jualeomad** [Galeon2098/CuidaME#188]
Página de inicio: 
-palabra "texto" en la nuca de la señora
-No es responsive

Sobre nosotros:
-No es responsive

Planes de precio:
-No es responsive
-Está en inglés
-Choose no lleva a ningún sitio

Iniciar sesión:
-En tamaño móvil quitar la imagen: no se ve bien la imagen y tener que deslizar para poder ver el formulario
-Cuando se inicia sesión lleva al inicio feo, debería llevar al home arreglado, o a ofertas

Registro cliente:
-Los errores no son homogéneos
-Desplegable de tipo de dependencia debe ser igual al de ofertas

Registro cuidador:
-Desplegable para tipo de público al que te diriges
-Cuadro de texto grande para experiencia
-Permite crearlo sin nombre, apellido ni email

**Comment by antsuagar** [comment]
En cuanto al registro de cuidador, en la parte de desplegable para tipo de público al que te diriges, ¿son los mismos tipos que a los que se dirigen las ofertas?

**Comment by antsuagar** [comment]
Al elegir un plan de precio, ¿a qué página debe redirigir? ¿A product_page?
