### ISSUE TITLE
Lista entregable

### ISSUE THREAD

**Issue by jualeomad** [Galeon2098/CuidaME#204]
Elaborar una lista (en un documento en el drive) de todos los documentos que se piden para este tercer entregable.

**Comment by manueljgranados** [comment]
@carlosdelrioperez, ¿en qué te has basado para hacer la lista de los documentos?

He incluido los documentos solicitados en la última Theory Pill.

Por favor, repasa feedbacks por si hubiera algo más que incluir.

**Comment by carlosdelrioperez** [comment]
Me he basado en el deliverable failure conditions y también he hablado con un compañero de otro grupo.

**Comment by manueljgranados** [comment]
Ok, cierro la tarea.

Gracias por el trabajo.
