### ISSUE TITLE
Crear el Storyboard

### ISSUE THREAD

**Issue by manueljgranados** [Galeon2098/CuidaME#213]
Crear el Storyboard basado en:
- la explicación dada por Carlos Müller en la plídora de la semana 7
- el propio Storyboard hecho por Lucía para la presentación de la semana pasada

**Comment by Lucperrom** [comment]
Perfecto, buen trabajo. Te lo acabo de añadir en el repositorio de documentación: https://github.com/CuidaMe-Org
