### ISSUE TITLE
feat: Calendario (Backend)

### ISSUE THREAD

**Issue by Lucperrom** [Galeon2098/CuidaME#235]
-Calendario personal del cuidador 
-Notificación por correo electrónico a modo de recordatorio de tarea diaria

**Comment by antsuagar** [comment]
Unas dudas:
- ¿El cuidador tiene que poder acceder al calendario desde un botón en el header o desde otro lugar?
- ¿Las notificaciones al correo deben de ser únicamente de las actividades de ese día? ¿O el propio cuidador puede elegir cuanto antes de la actividad quiere que se le notifique?
- La idea es que los calendarios de los cuidadores puedan ser compartidos con sus clientes. ¿Es eso necesario o se implementará más adelante?

**Comment by Lucperrom** [comment]
1ª Sí, lo suyo sería que tuviese acceso desde el header, es un botón que solo le aparecería a los cuidadores que tienen ese plan (eso se añadirá cuando la tarea de plan de precios esté terminada)
2ª Con que se le notifique el mismo día está bien, si te sobra tiempo y tienes ganas me parece que el poder elegir cuando se notifica es una idea interesante que se podría añadir.
3ª El calendario no es compartido, es un calendario personal del cuidador ya que en él podrá apuntar eventos de sus diferentes clientes para tenerlos más a mano.

Adicional: Como opcional podría estar bien que al añadir un evento al calendario uno de los campos fuese el cliente al que está relacionado ese evento y que saliese un desplegable con las personas con las que tiene chat. Pudiendo posteriormente filtrar la vista del calendario por cliente para que solo le apareciesen los eventos de ese cliente.

Esto último es completamente opcional, no tienes por qué hacerlo, se puede plantear como mejora si hubiese más actualizaciones en un futuro.
