### ISSUE TITLE
Informe de uso de Docusaurus

### ISSUE THREAD

**Issue by manueljgranados** [Galeon2098/CuidaME#240]
Al final del Sprint crear un informe de uso basado en el número de aportaciones de cada persona.

**Comment by antsuagar** [comment]
Con número de aportaciones, ¿se refiere al número de commits o al número de documentos?

**Comment by manueljgranados** [comment]
Buena pregunta... yo pondría número de commits ya que puede haber más de uno aportando en un mismo documento.
