### ISSUE TITLE
fix: Chat

### ISSUE THREAD

**Issue by manueljgranados** [Galeon2098/CuidaME#241]
- Si estás como Cuidador, cada mensaje que se manda muestra la fecha (aunque sea el mismo día)
- No se sabe cuando alguien solicita chat en caso de cuidador, ni cuando te aceptan o rechazan chat en caso de cliente, tienes que meterte en chats y verlo tu, (añadir algún aviso que te indique si se ha aceptado o rechazado la solicitud y en caso del cuidador, algún aviso por correo de que tiene solicitudes de chat nuevas o en la aplicación darle alguna visibilidad con el típico círculo rojo en chats de mensajes sin leer o un aviso de que tienes solicitudes nuevas)

Responsable: @dandiasua02 Ayuda: @jualeomad

**Comment by alvarocastellano** [comment]
Issue asumida en #276
