### ISSUE TITLE
fix: Ofertas

### ISSUE THREAD

**Issue by manueljgranados** [Galeon2098/CuidaME#242]
Al actualizar una oferta:
- en el despliegue del servidor salta error server 500
- en local no hay error pero no se actualiza nada

En el listado de Mis Ofertas no se pueden ver detalles (salvo que vayas a editarla). Hay que tener la opción de "Ver detalles" de cada oferta.

Al publicar una oferta no debe aparecer mi foto en el formulario de nueva oferta.

**Comment by fausto4VR** [comment]
¿Qué se refiere con: Al publicar una oferta no debe aparecer mi foto en el formulario de nueva oferta?

**Comment by manueljgranados** [comment]
![Captura de pantalla 2024-04-06 a las 21 13 32](https://github.com/Galeon2098/CuidaME/assets/37614464/f79f306d-c569-476c-932f-fefe60c6ac2e)

Este formulario, el de nueva oferta, no debe tener la imagen encima del nombre del cuidador (en este caso Cuidador01 no tiene imagen y aparece la by default)
