### ISSUE TITLE
fix: Detalles perfil

### ISSUE THREAD

**Issue by manueljgranados** [Galeon2098/CuidaME#244]
El detalle de perfil, tanto de cuidador como de cliente, tiene los nombres de campos en inglés (han de estar en español)

En la edición del perfil de cuidador los campos Experiencia y Formación aparecen con un tamaño muy grande.  Se puede reducir manualmente pero debe aparecer con un tamaño de no más de 4 líneas (permitiendo que manualmente se pueda seguir modificando su tamaño)

**Comment by alvarocastellano** [comment]
Tarea asumida en issue #276 fix frontend
