### ISSUE TITLE
fix: Mapa

### ISSUE THREAD

**Issue by manueljgranados** [Galeon2098/CuidaME#245]
El buscador del mapa no es responsive.

Cuando el en mapa buscas una dirección te lleva a la zona pero no muestra la dirección exacta con un marcador.

Al crear una oferta la población no está asociada con la calle ni el mapa... es un dato suelto que no influye en la dirección de la oferta en el mapa.

Especificar el formato correcto de la dirección.

**Comment by alvarocastellano** [comment]
Asumida en fix Frontend
