### ISSUE TITLE
fix: Frontend

### ISSUE THREAD

**Issue by manueljgranados** [Galeon2098/CuidaME#246]
Uno de los nombres de las valoraciones que aparecen en Home está repetido (María Suárez), cambiar uno de los nombres.

La imagen de fondo no se ajusta al 100% del width de la pantalla, en pantallas de gran tamaño a la derecha de la imagen sale un fondo azul oscuro

Footer muy grande: en pantallas de menor tamaño no mostrar el texto que aparece bajo "CuidaME"

**Comment by alvarocastellano** [comment]
se cierra, tarea añadida a la issue #262
