### ISSUE TITLE
fix: FAQ

### ISSUE THREAD

**Issue by alvarocastellano** [Galeon2098/CuidaME#261]
- No es responsive: cuando abres una pregunta de un video se cortan las palabras, esto pasa porque el video al tener opción de pantalla completa, las dimensiones son mayorees que el resto. No pasa nada por que dentro del recuadro se vea pequeño

- Modificar la pregunta de: ¿Me pueden pagar a través de la aplicación? No, todos los pagos entre usuario y cuidador no son mediante la aplicación, son como concreten usuario-cuidador, ya sea vía Bizum, metálico o transferencia bancaria, pero en ningún caso a través del sistema. Esto se debe a que podrías contratar un cuidador a largo plazo, lo que significaría añadir una suscripción al cuidadorr, lo cual no está contemplado en CuidaME. Lo único que se paga mediante la aplicación son los distintos planes de precio

- Las preguntas relacionadas con los distintos planes de precios,: Qué incluye el plan basico,avanzado y profesional, hacer distinción entre usuario cuidador y usuario cliente, con poner lo que añadió Lucía en la descripción de la issue de planes de precios (#206 ) sería suficiente

- Pregunta de ¿Cómo funciona la cancelación y renovación de los planes de suscripción? Contrasstar con el encargado de planes de precios para asegurarse de que está implementado así

**Comment by Lucperrom** [comment]
La tarea fix: FAQ se ha incluido en la tarea Corrección de hotfix #262
