### ISSUE TITLE
fix: Frontend

### ISSUE THREAD

**Issue by Lucperrom** [Galeon2098/CuidaME#276]
-Mapa: Barra de búsqueda no responsive. Cuando en el mapa buscas una dirección te lleva a la zona, pero no te señala que sea el sitio, estaría bien que lo destacase con algún tipo de puntero. Al crear una oferta la población no está asociada con el mapa. Especificar el formato de la dirección. Añadir autocompletado para no tener que poner la calle entera.

-Perfil: nombres de campo en inglés debe estar en español. 
En el caso de cuidador, los campos de experiencia y formación aparecen demasiado grande. Opción: intentar poner el formulario más ancho para darle más espacio a los inputs a lo largo en lugar de a lo alto. Quitar número de la seguridad social. El desplegable del menú pierde el fondo y se sobrepone al contenido (revisar si ocurre en más páginas).

-General: La mayoría de las imágenes que salen son de personas mayores, poner mayor variedad asociada a nuestros tipos de clientes.

- Detalles de la oferta: Añadir botón "ver perfil" que te lleve al perfil del cuidador, en las valoraciones del cuidador. Uniformidad de botones y texto. La media de valoraciones cambio -> en lugar de ponerlo con estrellas poner la media en número con un emoticono de una estrella al lado para que refleje que es la valoración media.

-En la foto de inicio de cuidame se muestran de ejemplo tres valoraciones: dos de ellas están puestas a nombre de "María Suárez" . Además si el monitor es más grande la imagen se ve estirada.

-PANTALLAZOOOO: si NO estás loggeado entras en ofertas y te metes en detalles de una oferta sale pantallazo de error: Field 'id' expected a number but got <SimpleLazyObject: <django.contrib.auth.models.AnonymousUser object at 0x3e70c7df1720>>.

-Planes de precio: cuando tienes un plan superior, bloquear el botón del plan o planes inferiores. Mostrar en la parte superior el plan actual del que dispones.

-Navbar: añadir el botón de ofertas aunque no esté loggeado.

-Crear oferta: el título y la descripción deben ser texto y cuando te equivocas que no borre los campos que estaban bien.

-FAQ: si abres un faq nuevo que cierre el anterior habiendo solo uno abierto a la vez. Hacer más hincapié en las diferencias entre cuidador y cliente en la pregunta sobre planes de precio

-CHAT: si no tienes chat donde debería aparecer el listado poner un mensaje de "No tienes chat". Si eres cuidador y le das dos veces al sobre te lleva a una página sin nada.

-Google: Revisar si da error loggearte con un correo de google cuando ya hay una cuenta creada con ese correo. De ser así arreglarlo para que te envíe de vuelva a la página de inicio de sesión con un mensaje en la parte superior

**Comment by manueljgranados** [comment]
Homogeneizar información:
En el formulario de registro de cliente y de cuidador hay campos que se refieren al mismo dato pero tienen nombre diferente

"Nombre de usuario" (en cliente) cambiar a "Usuario"
"Apellido" (en cliente) cambiar a "Apellidos"
"Correo electrónico" (en cliente) cambiar a "Email"

**Comment by manueljgranados** [comment]
Resolución de la siguiente incidencia:
Se da de alta un usuario y se trata de acceder a la aplicación sin esperar al correo de confirmación.
Se muestra la pantalla que se adjunta.



![Image](https://github.com/Galeon2098/CuidaME/assets/37614464/05f26315-f3a4-4ddd-8b79-6422f9a64cb9)



Resolución: Hay que mostrar una pantalla genérica, que no muestre información sobre el código de la aplicación

**Comment by fausto4VR** [comment]
Todo ha sido implementado con éxito excepto alguna de las exigencias con el mapa. Eso sí, el hecho de hacerlo responsive si se ha conseguido
