### ISSUE TITLE
UML

### ISSUE THREAD

**Issue by Lucperrom** [Galeon2098/CuidaME#51]

**Comment by manueljgranados** [comment]
Realizar el diagrama UML de los casos de uso core

Especialmente importante que queden bien definidos los campos necesarios en cada clase.

Hacedlo entre los dos y dadme reporte al final de cada día de cómo váis.

Tengamos en cuenta que hay compañeros que necesitan nuestro trabajo para terminar el suyo y (para más presión) todo debe estar terminado (o casi) este lunes por la mañana para que los encargados de la presentación la puedan montar.

Cualquier duda no os cortéis en preguntarme.

**Comment by manueljgranados** [comment]
Documento completo y bien definido.

Buen trabajo.
