### ISSUE TITLE
Incluir en doc de costes capex y opex

### ISSUE THREAD

**Issue by alvarocastellano** [Galeon2098/CuidaME#88]

**Comment by alvarocastellano** [comment]
Hay que incluir en el documento de costes, (Documentación/entregable 1), CAPEX (todo lo que capitalizas: infraestructura propia, coste de licencias compradas, coste de personal, coste de amortización..), OPEX (todo lo que te cuesta mantener operativo y proveer ese servicio: hosting, mantenimiento, mejoras, customer support, marketing…) y estimaciones de gastos e ingresos (coste actual, coste esperado y cómo evoluciona el coste según el número de usuarios, mirando el github actions. Poner tres casos: pesimista, realista y optimista).

**Comment by crigarher** [comment]
hecho
