### ISSUE TITLE
Anexo para commitment agreement

### ISSUE THREAD

**Issue by alvarocastellano** [Galeon2098/CuidaME#95]

**Comment by alvarocastellano** [comment]
En el commitment agreement indicar los casos donde no se desea sacar el 10. También indicar ahí los responsables de las tareas (¿enlace a issues?)

**Comment by manueljgranados** [comment]
Respecto al comentario anterior:
- de preferencia las tareas tendrán sólo un usuario asignado
- si tiene varios ha de haber obligatoriamente UN RESPONSABLE PRINCIPAL
- la asignación de RESPONSABLE DE ISSUE se hará en comentarios haciendo uso de su mención (para asegurarnos que se da por enterado) (mención: @ + usuario github) indicando que es el responsable de la issue

**Comment by alvarocastellano** [comment]
Anexo del commitment agreement realizado y en vigor para el S2.
