### ISSUE TITLE
Arreglar frontend semana 1

### ISSUE THREAD

**Issue by alvarocastellano** [Galeon2098/CuidaME#98]

**Comment by alvarocastellano** [comment]
En vez de ponerlo por pixeles, ponerlo por porcentajes

**Comment by Lucperrom** [comment]
-Corregir todo para que salga en inglés y ponerlo en español.
-Página de mensaje de error estética.
-Los atributos de "tipo cliente" y "tipo oferta" deben ser desplegables donde elegir la opción.
-Botones y letras más grandes (necesitamos que nuestros abuelitos puedan verlos bien).
-Intentar aprovechar más la pantalla (más de la mitad de la pantalla la suele ocupar una imagen).
