### ISSUE TITLE
Arreglar backend semana 1

### ISSUE THREAD

**Issue by alvarocastellano** [Galeon2098/CuidaME#99]
- Barra de navegación -> Añadir apartados según cuidador o cliente. (Ej. el botón "Crear oferta" visible para cuidador, pero no para cliente).  ✅
- Offer (publicar) -> No permitir que un cliente pueda publicar (restricción al principio del método). + No permitir publicar más de 5 ofertas. ✅
- Offer (editar) -> Deben aparecer los datos rellenos (Ahora salen vacíos así que de querer editar un apartado habría que rellenarlos todos). ✅
- Offer (borrado) -> Hubo un despiste y no se implementó, añadirlo ✅
- Perfill -> No permitir la edición si no es el propietario del perfil. ✅
- Botón en el listado de ofertas para que lo lleve a editar ✅
- Al hacer login redirigir a otra página (home) ✅

- Revisar que todos los errores se capturan con un try catch para poder dirigirlo a una página de error estética. ✅

**Comment by Lucperrom** [comment]
-Barra de navegación -> Añadir apartados según cuidador o cliente. (Ej. el botón "Crear oferta" visible para cuidador, pero no para cliente).
-Offer (publicar) -> No permitir que un cliente pueda publicar (restricción al principio del método). + No permitir publicar más de 5 ofertas.
-Offer (editar) -> Deben aparecer los datos rellenos (Ahora salen vacíos así que de querer editar un apartado habría que rellenarlos todos).
-Offer (borrado) -> Hubo un despiste y no se implementó, añadirlo.
-Perfill -> No permitir la edición si no es el propietario del perfil.
-Revisar que todos los errores se capturan con un try catch para poder dirigirlo a una página de error estética.
